config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :passwords, only: [:new, :edit, :create, :update]

  root 'sessions#new'
end

app/models/user.rb
class User < ActiveRecord::Base
  TOKEN_EXPIRES_IN = 6.hours
  has_secure_password

  validates :password, presence: true, on: :create, length: { minimum: 8 }
  validates :password, length: { minimum: 8 }, allow_nil: true, on: :update

  validates :name, length: { minimum: 5 }, on: :update

  validates :email, presence: true, uniqueness: true, format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  before_create :extract_name, :generate_token

  def token_reset
    generate_token(:reset_token)
    self.reset_token_sent_at = Time.zone.now
    save!
  end

  private

  def extract_name
    self.name = email.split('@').first
  end

  def generate_token(column = :token)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_token!(cookies[:auth_token]) if cookies[:auth_token]
  end

  private

  def must_login
    unless current_user
      flash[:danger] = "Please login!"
      redirect_to login_path
    end
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :find_user, only: [:edit, :update]

  def update
    if @user.reset_token_sent_at < User::TOKEN_EXPIRES_IN.ago
      redirect_to new_password_path, alert: "Token has expired"
    elsif @user.update_attributes(user_params)
      redirect_to root_url, notice: "Password has been reset!"
    else
      render :edit
    end
  end

  def create
    user = User.find_by_email(params[:email])
    if user
      UserMailer.reset_password(user).deliver if user.token_reset
      message = "Reset password email has been sent"
    else
      message = "Cannot find the user" 
    end
    redirect_to root_url, notice: message
  end

  private

  def find_user
    @user = User.find_by_reset_token!(params[:id])
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      cookies[:auth_token] = user.token
      redirect_to user_path(user), notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:update, :edit, :show]
  before_action :must_login, only: [:update, :edit, :show]

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(create_params)
    if @user.save
      UserMailer.welcome(@user).deliver
      cookies[:auth_token] = @user.token
      redirect_to login_path
    else
      render :new
    end
  end

  def update
    if @user.update_attributes(update_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def create_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def update_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

  def find_user
    @user ||= User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | IncubitRegSystem
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    - if current_user
      |  Signed in as #{link_to(current_user.name.to_s, user_path(current_user))} | #{link_to("Logout", logout_path, method: :delete)}
    - else
      |  Already have an account? #{link_to('Login', login_path)} | New User? #{link_to('Create an account', signup_path)}
    br
    - flash.each do |type, message|
      = message
    = yield

app/views/users/_errors.html.slim
- if user.errors.any?
  .error_messages
    h2
      | Errors
    ul
      - user.errors.full_messages.each do |message|
        li
          = message

app/views/users/edit.html.slim
h1
  | Edit profile
= form_for @user do |form|
  = render 'errors', user: @user
  .field
    = form.label :name
    br
    = form.text_field :name
  .field
    = form.label :email
    br
    = @user.email
  .field
    = form.label :password
    br
    = form.password_field :password
  .field
    = form.label :password_confirmation
    br
    = form.password_field :password_confirmation
  br
  = form.submit "Update"
  = link_to('Back', user_path(@user))

app/views/users/new.html.slim
h1
  | Sign Up
= form_for @user do |form|
  = render 'errors', user: @user
  .field
    = form.label :email
    br
    = form.text_field :email
  .field
    = form.label :password
    br
    = form.password_field :password
  .field
    = form.label :password_confirmation
    br
    = form.password_field :password_confirmation
  br
  .actions
    = form.submit 'Sign Up'

app/views/users/show.html.slim
p
  b
    | Name:
  = @user.name
p
  b
    | Email:
  = @user.email
= link_to('Edit', edit_user_path(@user))